### ISSUE TITLE
Parameter  value define

### ISSUE THREAD

**Issue by ddeevvaa** [azwhikaru/Action-TWRP-Builder#53]
Big azwhikaru,

need help for use this.

For a new device,how to define the value for this table.
the Example can not be understood why it is it.
do we have a tg group.look forard reply.

Name	Description	Example
MANIFEST_URL	Source address	https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
MANIFEST_BRANCH	Source branch	twrp-12.1
DEVICE_TREE_URL	Device address	https://github.com/TeamWin/android_device_asus_I003D
DEVICE_TREE_BRANCH	Device branch	android-12.1
DEVICE_PATH	Device location	device/asus/I003D
COMMON_TREE_URL	Common tree address	https://github.com/TeamWin/android_device_asus_sm8250-common
COMMON_PATH	Common tree location	device/asus/sm8250-common
DEVICE_NAME	Model name	I003D
MAKEFILE_NAME	Makefile name	twrp_I003D
BUILD_TARGET	Build Target Partition (boot/recovery/vendorboot)	recovery

**Comment by lopestom** [comment]
https://gist.github.com/lopestom/d85ce99bb244d308c5e681db31018626#file-using-online-resource-to-build-custom-recovery-iii-md
