### ISSUE TITLE
Recovery.img does not exist

### ISSUE THREAD

**Issue by YZ-Bruh** [azwhikaru/Action-TWRP-Builder#58]
Created but recovery.img does not exist among the files!
![Screenshot_20230731_172153](https://github.com/azwhikaru/Action-TWRP-Builder/assets/131263805/aeb50d8c-452c-464b-99ca-86a82a3fa03e)

Then I realized this;
![Screenshot_20230731_171901](https://github.com/azwhikaru/Action-TWRP-Builder/assets/131263805/5bd38bd3-7c4a-4f03-9ebc-16863937b72f)

How can I fix? Can you help me please?
Device Tree; https://github.com/YZ-Bruh/android_device_tcl_tb8765ap1_bsp

**Comment by azwhikaru** [comment]
your device name should be tb8765ap1_bsp not 8088X

**Comment by azwhikaru** [comment]
seems you have solved it. close
