### ISSUE TITLE
Building Recovery Error

### ISSUE THREAD

**Issue by akifakif32** [azwhikaru/Action-TWRP-Builder#60]
Run source build/envsetup.sh
including device/infinix/Infinix-X6833B/vendorsetup.sh
/home/runner/work/Action-TWRP-Builder/Action-TWRP-Builder/workspace/device/infinix/Infinix-X6833B/vendorsetup.sh:8: add_lunch_combo is obsolete. Use COMMON_LUNCH_CHOICES in your AndroidProducts.mk instead.
/home/runner/work/Action-TWRP-Builder/Action-TWRP-Builder/workspace/device/infinix/Infinix-X6833B/vendorsetup.sh:9: add_lunch_combo is obsolete. Use COMMON_LUNCH_CHOICES in your AndroidProducts.mk instead.
/home/runner/work/Action-TWRP-Builder/Action-TWRP-Builder/workspace/device/infinix/Infinix-X6833B/vendorsetup.sh:10: add_lunch_combo is obsolete. Use COMMON_LUNCH_CHOICES in your AndroidProducts.mk instead.
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
device/infinix/Infinix-X6833B/AndroidProducts.mk:11: error: device/infinix/Infinix-X6833B: twrp_Infinix-X6833B-user: Invalid variant: X6833B.
18:07:29 dumpvars failed with: exit status 1
Device Infinix not found. Attempting to retrieve device repository from TeamWin Github (http://github.com/TeamWin).
Repository for Infinix not found in the TeamWin Github repository list.
If this is in error, you may need to manually add it to your .repo/local_manifests/roomservice.xml
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
device/infinix/Infinix-X6833B/AndroidProducts.mk:11: error: device/infinix/Infinix-X6833B: twrp_Infinix-X6833B-user: Invalid variant: X6833B.
18:07:31 dumpvars failed with: exit status 1
build/make/core/version_defaults.mk:56: warning: Invalid TARGET_PLATFORM_VERSION 'eng', must be one of
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:68:
build/make/core/version_defaults.mk:57: error: SP2A.
18:07:31 dumpvars failed with: exit status 1

** Don't have a product spec for: 'twrp_Infinix'
** Do you have the right repo manifest?

Error: Process completed with exit code 1.

I did not understand what I should do, can you help me?

**Comment by lopestom** [comment]
- Change the name `twrp_Infinix-X6833B.mk` to `twrp_X6833B.mk`
- Change https://github.com/akifakif32/android_device_infinix_Infinix-X6833B/blob/twrp-12.1/twrp_Infinix-X6833B.mk to
```
PRODUCT_DEVICE := X6833B
PRODUCT_NAME := twrp_X6833B
```
- Change https://github.com/akifakif32/android_device_infinix_Infinix-X6833B/blob/twrp-12.1/BoardConfig.mk to
`DEVICE_PATH := device/infinix/X6833B`
- Change https://github.com/akifakif32/android_device_infinix_Infinix-X6833B/blob/5203e793f8d7268bdbcc75af860f0a060567ddf7/device.mk#L8C1-L8C44
`LOCAL_PATH := device/infinix/X6833B`
- Change your name repo [android_device_infinix_Infinix-X6833B](https://github.com/akifakif32/android_device_infinix_Infinix-X6833B/tree/twrp-12.1)
/ to android_device_infinix_X6833B

The problem is not from [Action-TWRP-Builder](https://github.com/azwhikaru/Action-TWRP-Builder) but the Source Code by TeamWin not accept the symbol `-` to makefile/search/compile.

**Comment by akifakif32** [comment]
yes, thank to you I solved it but now I am encountering a different problem

**Comment by akifakif32** [comment]
Run source build/envsetup.sh
including device/infinix/X6833B/vendorsetup.sh
/home/runner/work/Action-TWRP-Builder/Action-TWRP-Builder/workspace/device/infinix/X6833B/vendorsetup.sh:8: add_lunch_combo is obsolete. Use COMMON_LUNCH_CHOICES in your AndroidProducts.mk instead.
/home/runner/work/Action-TWRP-Builder/Action-TWRP-Builder/workspace/device/infinix/X6833B/vendorsetup.sh:9: add_lunch_combo is obsolete. Use COMMON_LUNCH_CHOICES in your AndroidProducts.mk instead.
/home/runner/work/Action-TWRP-Builder/Action-TWRP-Builder/workspace/device/infinix/X6833B/vendorsetup.sh:10: add_lunch_combo is obsolete. Use COMMON_LUNCH_CHOICES in your AndroidProducts.mk instead.
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
In file included from build/make/target/product/telephony_vendor.mk:24:
device/infinix/X6833B/device.mk:24: error: PRODUCT_STATIC_BOOT_CONTROL_HAL is obsolete. Use shared library module instead. See https://android.googlesource.com/platform/build/+/master/Changes.md#PRODUCT_STATIC_BOOT_CONTROL_HAL.
20:55:09 dumpvars failed with: exit status 1
Device X6833B not found. Attempting to retrieve device repository from TeamWin Github (http://github.com/TeamWin).
Repository for X6833B not found in the TeamWin Github repository list.
If this is in error, you may need to manually add it to your .repo/local_manifests/roomservice.xml
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
In file included from build/make/target/product/telephony_vendor.mk:24:
device/infinix/X6833B/device.mk:24: error: PRODUCT_STATIC_BOOT_CONTROL_HAL is obsolete. Use shared library module instead. See https://android.googlesource.com/platform/build/+/master/Changes.md#PRODUCT_STATIC_BOOT_CONTROL_HAL.
20:55:10 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
In file included from build/make/target/product/telephony_vendor.mk:24:
device/infinix/X6833B/device.mk:24: error: PRODUCT_STATIC_BOOT_CONTROL_HAL is obsolete. Use shared library module instead. See https://android.googlesource.com/platform/build/+/master/Changes.md#PRODUCT_STATIC_BOOT_CONTROL_HAL.
20:55:11 dumpvars failed with: exit status 1

** Don't have a product spec for: 'twrp_X6833B'
** Do you have the right repo manifest?

Error: Process completed with exit code 1.
