### ISSUE TITLE
Ninja error

### ISSUE THREAD

**Issue by akifakif32** [azwhikaru/Action-TWRP-Builder#61]
FAILED: ninja: 'device/infinix/X6833B/prebuilt/kernel', needed by 'out/target/product/X6833B/kernel', missing and no known rule to make it
23:08:43 ninja failed with: exit status 1
Error: Process completed with exit code 1.
What should I do?

**Comment by akifakif32** [comment]
I think there was an error while I was trying to unpack boot.img so I was nat able to extract kernel from it and I have not got a windows/linux pc or laptop. Can anybody extract kernel from this boot.img: https://file.io/by6piPR0sVFL

**Comment by azwhikaru** [comment]
kernel is in boot.img, dtb is in vendor_boot.img. provide your boot.img

**Comment by akifakif32** [comment]
> kernel is in boot.img, dtb is in vendor_boot.img. provide your boot.img

But I am using vendor_boot.img as my twrp tree, is it a problem? 
Here is my boot.img: https://file.io/M5xJBsZY2uGf
Thank you

**Comment by azwhikaru** [comment]
extracted from boot.img: https://file.io/5KhoHZ6YF4nM

use boot.img to make it. we may need somethings in vendor_boot.img, not full of it

**Comment by azwhikaru** [comment]
put boot.img-kernel in device/infinix/X6833B/prebuilt/kernel to fix your problem

**Comment by akifakif32** [comment]
> put boot.img-kernel in device/infinix/X6833B/prebuilt/kernel to fix your problem

You are the best, thanks to I was able to create twrp boot.img but as you can see it is a boot.img no recovery.img do you know how I can boot twrp?

**Comment by azwhikaru** [comment]
try `fastboot boot twrp.img`

if doesn't work, try flashing your twrp.img (boot.img) to the boot `fastboot flash boot_a twrp.img`

if current slot is _b, use `fastboot flash boot_b twrp.img`

use `fastboot getvar current-slot` to get current slot

**Comment by akifakif32** [comment]
Thank you.

**Comment by akifakif32** [comment]
But it stuck on bootlogo, what can the problem be?

**Comment by azwhikaru** [comment]
check your device tree, but I can't help you anymore because I don't have the same device as you
