### ISSUE TITLE
build success but "Pattern 'workspace/out/target/product/mcaymanlm/recovery.img' does not match any files."

### ISSUE THREAD

**Issue by lonelyicer** [azwhikaru/Action-TWRP-Builder#66]
![image](https://github.com/azwhikaru/Action-TWRP-Builder/assets/63995099/69f91c7f-225d-441f-ad01-a70df2a01b8f)
![image](https://github.com/azwhikaru/Action-TWRP-Builder/assets/63995099/507d03ef-6071-4e48-a63b-d6534ee01071)
![image](https://github.com/azwhikaru/Action-TWRP-Builder/assets/63995099/e0b001fa-d6a1-4c1b-aaca-85667e515692)

device tree: https://github.com/lonelyicer/android_device_lge_mcaymanlm

**Comment by lonelyicer** [comment]
> I checked your record, is because twrp was not built yet ![image](https://user-images.githubusercontent.com/37921907/268966716-eff1a58f-45bd-4386-8899-36e5aeab5ff9.png) obviously, some errors have occurred ![image](https://user-images.githubusercontent.com/37921907/268966651-4ef27b98-bc64-4481-bf33-ab08c3734a68.png)

I tried to build OFPR using another repository and it also didn't generate recovery.img correctly 
https://github.com/lonelyicer/Action-OFRP-Builder/releases/tag/6251241522

how can i fix it?

**Comment by lonelyicer** [comment]
https://github.com/lonelyicer/Action-OFRP-Builder/actions/runs/6251241522/job/16971929761
log here

**Comment by azwhikaru** [comment]
I cant help you fix device tree, sorry

**Comment by lopestom** [comment]
> https://github.com/lonelyicer/Action-OFRP-Builder/actions/runs/6251241522/job/16971929761 log here

> > I checked your record, is because twrp was not built yet image obviously, some errors have occurred image
> 
> I tried to build OFPR using another repository and it also didn't generate recovery.img correctly https://github.com/lonelyicer/Action-OFRP-Builder/releases/tag/6251241522
> 
> how can i fix it?

Simple. Your DT has `BOARD_USES_RECOVERY_AS_BOOT := true`
Your [Action-OFRP-Builder](https://github.com/lonelyicer/Action-OFRP-Builder) show:
  `lunch twrp_mcaymanlm-eng && make clean && mka adbd recoveryimage -j$(nproc --all)`
https://github.com/lonelyicer/Action-OFRP-Builder/actions/runs/6251241522/job/16971929761#step:10:7

You not compile recoveryimage since you use Virtual A/B so bootimage should compile!
https://github.com/lonelyicer/android_device_lge_mcaymanlm/blob/c33e0d4820e76ac6719c471ccaf124eca5449abb/BoardConfig.mk#L13

The ERROR is your!

**Comment by yunzimo** [comment]
> > https://github.com/lonelyicer/Action-OFRP-Builder/actions/runs/6251241522/job/16971929761 log here
> 
> > > I checked your record, is because twrp was not built yet image obviously, some errors have occurred image
> > 
> > 
> > I tried to build OFPR using another repository and it also didn't generate recovery.img correctly https://github.com/lonelyicer/Action-OFRP-Builder/releases/tag/6251241522
> > how can i fix it?
> 
> Simple. Your DT has `BOARD_USES_RECOVERY_AS_BOOT := true` Your [Action-OFRP-Builder](https://github.com/lonelyicer/Action-OFRP-Builder) show: `lunch twrp_mcaymanlm-eng && make clean && mka adbd recoveryimage -j$(nproc --all)` https://github.com/lonelyicer/Action-OFRP-Builder/actions/runs/6251241522/job/16971929761#step:10:7
> 
> You not compile recoveryimage since you use Virtual A/B so bootimage should compile! https://github.com/lonelyicer/android_device_lge_mcaymanlm/blob/c33e0d4820e76ac6719c471ccaf124eca5449abb/BoardConfig.mk#L13
> 
> The ERROR is your!

Bro, I also have the same problem. Can you please check where my problem is? Thank you very much.

https://github.com/yunzimo/Action-TWRP-Builder/actions/runs/8586763156/job/23529608893

and My DT

https://github.com/yunzimo/android_device_vivo_PD2121
