### ISSUE TITLE
"vendor/omni/config/common.mk" does not exist

### ISSUE THREAD

**Issue by ruigegoat** [azwhikaru/Action-TWRP-Builder#74]
Here's the error:
![image](https://github.com/azwhikaru/Action-TWRP-Builder/assets/72699183/61389460-618a-4f06-9c82-256f78d13607)

Here's the device tree:
[twrp_device_general_G512](https://www.github.com/ruigegoat/twrp_device_general_G512)

I've created the device tree using twrpdtgen and I'm using these arguments on the script:
![image](https://github.com/azwhikaru/Action-TWRP-Builder/assets/72699183/c8de396e-9310-43aa-87f9-700a00bbe5dd)

Any help is appreciated.

**Comment by yunzimo** [comment]
> Here's the error: ![image](https://private-user-images.githubusercontent.com/72699183/281500094-61389460-618a-4f06-9c82-256f78d13607.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MzgxODUsIm5iZiI6MTcxMjQzNzg4NSwicGF0aCI6Ii83MjY5OTE4My8yODE1MDAwOTQtNjEzODk0NjAtNjE4YS00ZjA2LTljODItMjU2Zjc4ZDEzNjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDIxMTEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZDAzNjIwZDI2ZTI1ODRjMDI0ZTY3OTYzMDY3YjNhZWRiNDc4ZTlmM2U0MDdkODI2Y2ZlY2Y3NDVlYmZlOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qAMtsJ0WfNPu7PZYE4tdSVcVdoaQgC3V6SQBRjhhh0U)
> 
> Here's the device tree: [twrp_device_general_G512](https://www.github.com/ruigegoat/twrp_device_general_G512)
> 
> I've created the device tree using twrpdtgen and I'm using these arguments on the script: ![image](https://private-user-images.githubusercontent.com/72699183/281500554-c8de396e-9310-43aa-87f9-700a00bbe5dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MzgxODUsIm5iZiI6MTcxMjQzNzg4NSwicGF0aCI6Ii83MjY5OTE4My8yODE1MDA1NTQtYzhkZTM5NmUtOTMxMC00M2FhLTg3ZjktNzAwYTAwYmJlNWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDIxMTEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYzlhMTczNmMxMjBmMGI5NmUwZjg0NDc1NzQ3OGRmNzY1ODg4NTNlYWI0MWQyMmEzZjI2YWZjNzk4YzIyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0vrMc5AwtTebuDAfzWB1W4c3uiEx_QKM7NN8_zENB6E)
> 
> Any help is appreciated.

Have you solved this problem?

**Comment by yunzimo** [comment]
I tried changing onmi to twrp, and the error message disappeared.
