### ISSUE TITLE
git cannot sync download manifest

### ISSUE THREAD

**Issue by jisuanjiQAQ** [azwhikaru/Action-TWRP-Builder#81]
I got an error when running the fox build script
fatal: cannot obtain manifest https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
================================================== ==============================
Repo command failed: UpdateManifestError
Unable to sync manifest default.xml

manifests:
fatal: couldn't find remote ref refs/heads/12.1
manifests: sleeping 4.0 seconds before retrying
Error: Process completed with exit code 1.

**Comment by azwhikaru** [comment]
it's not a script bug
