### ISSUE TITLE
无法找到或生成 /home/runner/work/Action-TWRP-builder/Action-TWRP-builder/workspace/out/host/linux-x86/bin/zopflipng 

### ISSUE THREAD

**Issue by momo54181** [azwhikaru/Action-TWRP-Builder#82]
无法找到或生成 /home/runner/work/Action-TWRP-builder/Action-TWRP-builder/workspace/out/host/linux-x86/bin/zopflipng 

Log:
including device/vivo/k71v1_64_bsp/vendorsetup.sh
device/vivo/k71v1_64_bsp/vendorsetup.sh:8: add_lunch_combo is obsolete. Use COMMON_LUNCH_CHOICES in your AndroidProducts.mk instead.
device/vivo/k71v1_64_bsp/vendorsetup.sh:9: add_lunch_combo is obsolete. Use COMMON_LUNCH_CHOICES in your AndroidProducts.mk instead.
device/vivo/k71v1_64_bsp/vendorsetup.sh:[10](https://github.com/momo54181/Action-TWRP-builder/actions/runs/7593999666/job/20685055915#step:16:11): add_lunch_combo is obsolete. Use COMMON_LUNCH_CHOICES in your AndroidProducts.mk instead.
ccache found and CCACHE_EXEC has been set to : /usr/bin/ccache
WARNING: device/vivo/k71v1_64_bsp/omni.dependencies file not found
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=16.1.0
TARGET_PRODUCT=omni_k71v1_64_bsp
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-6.2.0-1018-azure-x86_64-Ubuntu-22.04.3-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=QQ3A.200805.001
OUT_DIR=/home/runner/work/Action-TWRP-builder/Action-TWRP-builder/workspace/out
ROM_BUILDTYPE=HOMEMADE
============================================
[11](https://github.com/momo54181/Action-TWRP-builder/actions/runs/7593999666/job/20685055915#step:16:12):21:41 Entire build directory removed.
#### build completed successfully (1 seconds) ####
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=16.1.0
TARGET_PRODUCT=omni_k71v1_64_bsp
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-6.2.0-1018-azure-x86_64-Ubuntu-22.04.3-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=QQ3A.200805.001
OUT_DIR=/home/runner/work/Action-TWRP-builder/Action-TWRP-builder/workspace/out
ROM_BUILDTYPE=HOMEMADE
============================================

(https://github.com/momo54181/Action-TWRP-builder/actions/runs/7593999666/job/20685055915#step:16:398)] finishing build rules ...
vendor/omni/build/tasks/kernel.mk:111: warning: ***************************************************************
vendor/omni/build/tasks/kernel.mk:112: warning: * Using prebuilt kernel binary instead of source              *
vendor/omni/build/tasks/kernel.mk:113: warning: * THIS IS DEPRECATED, AND WILL BE DISCONTINUED                *
vendor/omni/build/tasks/kernel.mk:114: warning: * Please configure your device to download the kernel         *
vendor/omni/build/tasks/kernel.mk:115: warning: * source repository to 
vendor/omni/build/tasks/kernel.mk:116: warning: * for more information                                        *
vendor/omni/build/tasks/kernel.mk:117: warning: ***************************************************************
[100% 397/397] writing build rules ...
/home/runner/work/Action-TWRP-builder/Action-TWRP-builder/workspace/out/build-omni_k71v1_64_bsp-package.ninja is missing, regenerating...
[ 99% [398](https://github.com/momo54181/Action-TWRP-builder/actions/runs/7593999666/job/20685055915#step:16:399)/400] initializing packaging system ...
[ 99% [399](https://github.com/momo54181/Action-TWRP-builder/actions/runs/7593999666/job/20685055915#step:16:400)/[400](https://github.com/momo54181/Action-TWRP-builder/actions/runs/7593999666/job/20685055915#step:16:401)] including distdir.mk ...
[100% 400/400] writing packaging rules ...
Starting ninja...
FAILED: ninja: '/home/runner/work/Action-TWRP-builder/Action-TWRP-builder/workspace/out/host/linux-x86/bin/zopflipng', needed by '/home/runner/work/Action-TWRP-builder/Action-TWRP-builder/workspace/out/target/product/k71v1_64_bsp/obj/PACKAGING/recovery_text_res_intermediates/installing_text.png', missing and no known rule to make it
11:23:07 ninja failed with: exit status 1
Error: Process completed with exit code 1.

**Comment by azwhikaru** [comment]
it's not a script bug
