### ISSUE TITLE
Repo sync error

### ISSUE THREAD

**Issue by Sandeep2062** [azwhikaru/Action-TWRP-Builder#83]
![Screenshot 2024-02-12 000415](https://github.com/azwhikaru/Action-TWRP-Builder/assets/122968115/ec91101e-c3e8-4aba-9777-86639f52bcea)

Run repo sync -j$(nproc --all) --force-sync
  repo sync -j$(nproc --all) --force-sync
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/8.0.40[2](https://github.com/Sandeep2062/Action-TWRP-Builder_SHRP/actions/runs/7863650216/job/21454496689#step:10:2)-6/x6[4](https://github.com/Sandeep2062/Action-TWRP-Builder_SHRP/actions/runs/7863650216/job/21454496689#step:10:4)
    JAVA_HOME_8_X[6](https://github.com/Sandeep2062/Action-TWRP-Builder_SHRP/actions/runs/7863650216/job/21454496689#step:10:6)4: /opt/hostedtoolcache/Java_Zulu_jdk/8.0.402-6/x64
  
error: Cannot fetch phhusson/vendor_lptools from https://github.com/github.com/phhusson/vendor_lptools
error: Cannot fetch phhusson/vendor_lptools from https://github.com/github.com/phhusson/vendor_lptools

remote: Not Found
fatal: repository 'https://github.com/github.com/phhusson/vendor_lptools/' not found

phhusson/vendor_lptools:
remote: Not Found
fatal: repository 'https://github.com/github.com/phhusson/vendor_lptools/' not found
phhusson/vendor_lptools: sleeping 4.0 seconds before retrying
remote: Not Found
fatal: repository 'https://github.com/github.com/phhusson/vendor_lptools/' not found

why i am getting this error

**Comment by AntarcticShaurant** [comment]
Well as you can see, it searches for https://github.com/github.com, haha, let me see if i can find the error and make a pull request

**Comment by Sandeep2062** [comment]
umm no it got solved adding / solved it
thanks
![Screenshot 2024-02-14 163121](https://github.com/azwhikaru/Action-TWRP-Builder/assets/122968115/0f5dc768-ac92-4f12-b272-e322e4e0ece0)
![Screenshot 2024-02-14 163128](https://github.com/azwhikaru/Action-TWRP-Builder/assets/122968115/67a4a731-7459-4bbc-b69f-18ff48f9935a)
