### ISSUE TITLE
... Unable to create vendorboot image

### ISSUE THREAD

**Issue by kongdwm** [azwhikaru/Action-TWRP-Builder#95]
build/make/core/board_config.mk:902: error: Should not set BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT if not building vendor_boot image.

**Comment by kongdwm** [comment]
![Screenshot_2024-08-04-17-18-19-264_com microsoft emmx-edit](https://github.com/user-attachments/assets/700aa238-dab2-4467-bfd0-fdea0ba691f9)

**Comment by kongdwm** [comment]
![Uploading Screenshot_2024-08-04-17-20-17-821_com.microsoft.emmx-edit.jpg…]()

**Comment by kongdwm** [comment]
![Screenshot_2024-08-04-17-20-17-821_com microsoft emmx-edit](https://github.com/user-attachments/assets/4d027fd8-aec7-4d51-a107-10584194dffc)

**Comment by azwhikaru** [comment]
your device's problem, can't help you anymore
